### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by MatijaNovosel** [TarkovTracker/TarkovTracker#407]
After choosing any login method I am greeted by a white rectangle that displays loading indefinitely:

![image](https://github.com/TarkovTracker/TarkovTracker/assets/36193643/33b67be2-81b1-4a42-bc19-f4b88b534c39)

**Comment by JamieBunpup** [comment]
I'm experiencing this too, it sometimes works, but it's extremely inconsistent.

**Comment by lyricalcasanova** [comment]
Is there any more info on this? Has this been resolved?

**Comment by paytah232** [comment]
I have this too.
I tried:

- Removing all cookies and browser history
- Disabling adblock extensions
- Logging in with 3 different linked accounts (2 share 1 email address)

This didn't work for me. I also then tried using an incognito browser, and got the following response (Firebase same email but different sign in) on my first attempt, but then never got it again.
![image](https://github.com/TarkovTracker/TarkovTracker/assets/44075588/278b266a-3955-4c8d-89ac-a7478015396d)
At this point, I then tried the other account associated to my github email, but still, it doesn't work.

Also once 'logged in', the login page is empty, but log in hasn't occurred.
![image](https://github.com/TarkovTracker/TarkovTracker/assets/44075588/4ecf2113-59ee-4e49-9f22-fc09a07fea35)

I'm not sure if it would help, but perhaps a way to completely remove any links from all of my sign in methods to start again could be good (i.e a way to remove any links my accounts have with TarkovTracker and Firebase - Account Deletion)

**Comment by paytah232** [comment]
Playing in the console, once 'completing the login' and the entries go away, navigation to a page that isn't log in (i.e Home) and then back to login, the following TypError error occurs:
```
index.9136f70f.js:1 TypeError: S.auth.AuthCredential.fromJSON is not a function
    at fu (LoginInterface.a5dc2828.js:4:2219)
    at Ke (LoginInterface.a5dc2828.js:4:16090)
    at Wr (LoginInterface.a5dc2828.js:5:23185)
    at Yc (LoginInterface.a5dc2828.js:5:22983)
    at l.start (LoginInterface.a5dc2828.js:5:22587)
    at LoginInterface.a5dc2828.js:5:41921
    at index.9136f70f.js:1:29081
    at rs (index.9136f70f.js:1:14622)
    at lr (index.9136f70f.js:1:14701)
    at Zf.e.__weh.e.__weh (index.9136f70f.js:1:28961)
bM @ index.9136f70f.js:1
Ju @ index.9136f70f.js:1
rs @ index.9136f70f.js:1
lr @ index.9136f70f.js:1
Zf.e.__weh.e.__weh @ index.9136f70f.js:1
bA @ index.9136f70f.js:1
wA @ index.9136f70f.js:1
Promise.then (async)
vA @ index.9136f70f.js:1
IM @ index.9136f70f.js:1
NM @ index.9136f70f.js:1
_ @ index.9136f70f.js:1
DE @ index.9136f70f.js:1
Wg @ index.9136f70f.js:1
mA @ index.9136f70f.js:1
(anonymous) @ index.9136f70f.js:1
DE @ index.9136f70f.js:1
Wg @ index.9136f70f.js:1
mA @ index.9136f70f.js:1
(anonymous) @ index.9136f70f.js:1
DE @ index.9136f70f.js:1
Wg @ index.9136f70f.js:1
mA @ index.9136f70f.js:1
set value @ index.9136f70f.js:1
ee @ index.9136f70f.js:62
(anonymous) @ index.9136f70f.js:62
Promise.then (async)
S @ index.9136f70f.js:62
w @ index.9136f70f.js:62
a @ index.9136f70f.js:62
T @ VListItem.e53deda9.js:1
rs @ index.9136f70f.js:1
lr @ index.9136f70f.js:1
n @ index.9136f70f.js:1
```

Not sure if this might help with debugging or not, but I thought i'd post it anyway.

**Comment by DysektAI** [comment]
## Maintainer Needed
Calling upon @thaddeus for a speedy resolution. Without their help, this will most likely be impossible to fix fully, as no one else has access to firebase or account related management.
## Personal Experience
I have not had this issue yet. I do know a few others who quit using TarkovTracker due to this or similar issues.
```Progress being reset while logged in, misc. account issues, and login issues. (like this issue)```
### I urge for this to be prioritized and resolved asap to ensure the best experience for all.

## Help fix this or find a work around for now
For those of you who have this issue currently @MatijaNovosel @paytah232 @JamieBunpup the more info and data we can gather about this, the easier it will be to know where the issue originates, since there is not a known or consistent way to reproducible these issues if possible please fill out the below it will be invaluable. This may help find a work around, before a real fix can be implemented.

### When did you sign up for TarkovTracker? (If unsure please estimate)
A: 

### Did you make an account before or after using features of TarkovTracker?
A: 

### What method did you use to create an account? Google, GitHub, Twitter or Microsoft (Specify if you used more than one)
A: 

### Was your account working fine, then randomly started having issues or was there issue from the start?
A: 

### Have you tried using incognito mode / private browsing with all extensions disabled? (Just to rule out third party issues)
A: 

### Try deauthorizing the auth from the service you used to sign up and see if you can resign up as a possible work around
A: 

---
> [!IMPORTANT]  
> ### If anyone can find a way to reproduce this consistently, it would be help A LOT and be the fastest way to find a resolution.

**Comment by JamieBunpup** [comment]
Apologies for checking out of this thread for some time. I had zoned out from it as I managed to log in again eventually after many tries (I have no info on what parameters changed to allow login to be possible, sadly.)

When did you sign up for TarkovTracker? (If unsure please estimate)

A: Early 2024

Did you make an account before or after using features of TarkovTracker?

A: After.

What method did you use to create an account? Google, GitHub, Twitter or Microsoft (Specify if you used more than one)

A: Google for both accounts


Was your account working fine, then randomly started having issues or was there issue from the start?

A: When trying to make a different account to track progress on my alt account, that is when I ran into the issue.


Have you tried using incognito mode / private browsing with all extensions disabled? (Just to rule out third party issues)

A: Yes. I had issues regardless.


Try deauthorizing the auth from the service you used to sign up and see if you can resign up as a possible work around

A: I am frankly afraid of trying anything at this stage as it is currently working for me.

**Comment by Nipeno** [comment]
+1
Even tried on mobile and same issue

**Comment by paytah232** [comment]
I tried logging in with github today - this issue still persists, no idea what to do to fix it, but I still can't use the tool... 😢

**Comment by DysektAI** [comment]
This should not be an issue for my currently, self-maintained fork of the project here: <https://tarkovtracker.org/>

**Comment by paytah232** [comment]
@DysektAI Can confirm your site works. What is the difference that stops me being able to log in here i wonder.

**Comment by DysektAI** [comment]
> [@DysektAI](https://github.com/DysektAI?rgh-link-date=2025-03-25T10%3A02%3A34.000Z) Can confirm your site works. What is the difference that stops me being able to log in here i wonder.

Honestly cant say for sure but the error message you got I had only when I had the backend setup to "Link accounts with the same email" so for example using Github to login then Google after would throw an error saying you already have an account and to reset password or something similar, I just set it instead for now so each login method is using a fresh account even if the email matches.

**Comment by DysektAI** [comment]
## Has your issue been resolved? @MatijaNovosel 
- **Yes** → please close this issue (use **Close issue** or **Close with comment** below).
- **No** → leave a short comment so others know it's still a problem.

> [!IMPORTANT]
> This repository and [TarkovTracker.io](https://TarkovTracker.io) are **currently unmaintained**.  
> It’s unlikely that new issues or pull requests will receive a response from the original maintainers.

### 👉 Looking for the active project?
- **Website:** [TarkovTracker.org](https://TarkovTracker.org)
- **Source code:** [tarkovtracker-org/TarkovTracker](https://github.com/tarkovtracker-org/TarkovTracker)
- **Open a new issue here:** https://github.com/tarkovtracker-org/TarkovTracker/issues/new/choose
- **Project status & changelog:** #455 

_Thanks for keeping things tidy and for using TarkovTracker!_
